// flow-typed signature: c99829a2603d840b049b113a429ce21f
// flow-typed version: <<STUB>>/@types/date-fns_v^2.5.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/date-fns' {
  declare module.exports: any;
}
