// flow-typed signature: 62282e645af2f5e0177c97835a9f2381
// flow-typed version: <<STUB>>/@types/dotenv_v^2.0.19/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/dotenv' {
  declare module.exports: any;
}
