// flow-typed signature: 2146c50ae3d6daa84e89d593ed196dee
// flow-typed version: <<STUB>>/@types/ramda_v^0.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ramda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ramda' {
  declare module.exports: any;
}
