// flow-typed signature: 3c890c848b4605026fc5cc1941f44939
// flow-typed version: <<STUB>>/@types/ramda_v^0.0.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ramda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ramda' {
  declare module.exports: any;
}
