// flow-typed signature: bafa35dc45375cdecdabbea153382751
// flow-typed version: <<STUB>>/@types/ramda_v^0.0.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ramda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ramda' {
  declare module.exports: any;
}
