// flow-typed signature: c7bf2baf02513dc116b1bc74e74f17d7
// flow-typed version: <<STUB>>/@types/request_v^0.0.33/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
