// flow-typed signature: a0ac3ad557aa16de2303a39427d3de18
// flow-typed version: <<STUB>>/@types/request_v^0.0.33/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
