// flow-typed signature: 0477b256410d3374787e7b153d1f6806
// flow-typed version: <<STUB>>/@types/request-promise-native_v^1.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request-promise-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request-promise-native' {
  declare module.exports: any;
}
