// flow-typed signature: 55ae3f8aebb8a76f8b3a14763ae3d7a3
// flow-typed version: <<STUB>>/async-retry_v^0.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-retry/build/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-retry/build/lib/index.js' {
  declare module.exports: $Exports<'async-retry/build/lib/index'>;
}
