// flow-typed signature: d47a2f86eac3fe4881ede33491473c1c
// flow-typed version: <<STUB>>/eslint-config-anvilabs_v^2.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-anvilabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-anvilabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-anvilabs/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-anvilabs/lodash' {
  declare module.exports: any;
}

declare module 'eslint-config-anvilabs/react-base' {
  declare module.exports: any;
}

declare module 'eslint-config-anvilabs/react-native' {
  declare module.exports: any;
}

declare module 'eslint-config-anvilabs/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-anvilabs/index' {
  declare module.exports: $Exports<'eslint-config-anvilabs'>;
}
declare module 'eslint-config-anvilabs/index.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs'>;
}
declare module 'eslint-config-anvilabs/jest.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs/jest'>;
}
declare module 'eslint-config-anvilabs/lodash.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs/lodash'>;
}
declare module 'eslint-config-anvilabs/react-base.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs/react-base'>;
}
declare module 'eslint-config-anvilabs/react-native.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs/react-native'>;
}
declare module 'eslint-config-anvilabs/react.js' {
  declare module.exports: $Exports<'eslint-config-anvilabs/react'>;
}
