// flow-typed signature: 5446692a47743537443d7e24853d7eec
// flow-typed version: <<STUB>>/lodash.words_v^4.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.words/index' {
  declare module.exports: $Exports<'lodash.words'>;
}
declare module 'lodash.words/index.js' {
  declare module.exports: $Exports<'lodash.words'>;
}
