// flow-typed signature: 1c29f6680343c822f878326266b45aa6
// flow-typed version: <<STUB>>/parent-package-json_v^2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parent-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parent-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parent-package-json/lib/index' {
  declare module.exports: any;
}

declare module 'parent-package-json/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parent-package-json/lib/index.js' {
  declare module.exports: $Exports<'parent-package-json/lib/index'>;
}
declare module 'parent-package-json/test/index.js' {
  declare module.exports: $Exports<'parent-package-json/test/index'>;
}
