// flow-typed signature: 0c43fe816bd26f43efd94823f8c3dce0
// flow-typed version: <<STUB>>/random-useragent_v^0.3.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-useragent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-useragent/scripts/create-data' {
  declare module.exports: any;
}

declare module 'random-useragent/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-useragent/index' {
  declare module.exports: $Exports<'random-useragent'>;
}
declare module 'random-useragent/index.js' {
  declare module.exports: $Exports<'random-useragent'>;
}
declare module 'random-useragent/scripts/create-data.js' {
  declare module.exports: $Exports<'random-useragent/scripts/create-data'>;
}
declare module 'random-useragent/test.js' {
  declare module.exports: $Exports<'random-useragent/test'>;
}
