// flow-typed signature: c27e9035eb2a06669b419d52de4f1555
// flow-typed version: <<STUB>>/similarity_v^1.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'similarity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'similarity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'similarity/example' {
  declare module.exports: any;
}

declare module 'similarity/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'similarity/example.js' {
  declare module.exports: $Exports<'similarity/example'>;
}
declare module 'similarity/index' {
  declare module.exports: $Exports<'similarity'>;
}
declare module 'similarity/index.js' {
  declare module.exports: $Exports<'similarity'>;
}
declare module 'similarity/test/index.js' {
  declare module.exports: $Exports<'similarity/test/index'>;
}
