// flow-typed signature: 2be7512edbcee526793d9282ff43a9af
// flow-typed version: <<STUB>>/standard-version_v^4.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-version/bin/cli' {
  declare module.exports: any;
}

declare module 'standard-version/command' {
  declare module.exports: any;
}

declare module 'standard-version/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-version/bin/cli.js' {
  declare module.exports: $Exports<'standard-version/bin/cli'>;
}
declare module 'standard-version/command.js' {
  declare module.exports: $Exports<'standard-version/command'>;
}
declare module 'standard-version/index' {
  declare module.exports: $Exports<'standard-version'>;
}
declare module 'standard-version/index.js' {
  declare module.exports: $Exports<'standard-version'>;
}
declare module 'standard-version/test.js' {
  declare module.exports: $Exports<'standard-version/test'>;
}
