// flow-typed signature: adb7956b2b9cf5d87f4c2dcfba03407a
// flow-typed version: <<STUB>>/type-detect_v^4.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'type-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'type-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'type-detect/type-detect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'type-detect/index' {
  declare module.exports: $Exports<'type-detect'>;
}
declare module 'type-detect/index.js' {
  declare module.exports: $Exports<'type-detect'>;
}
declare module 'type-detect/type-detect.js' {
  declare module.exports: $Exports<'type-detect/type-detect'>;
}
